name: lookfindr
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/intro/
    - assets/home/
    - assets/product/

fonts:
  - family: Hiatus
    fonts:
      - asset: assets/fonts/Hiatus-Regular.ttf
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Medium.ttf
      - asset: assets/fonts/Montserrat-SemiBold.ttf